name: PHP 8.0 Tests
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        name: PHP 8.0 Tests
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
            - run: composer install
            - run: vendor/bin/phpunit